### PR TITLE
Run7/step08

### PR DESCRIPTION
**Pull request by seanmacb**
File structure determined from [confluence page](https://confluence.lsstcorp.org/display/CAM/Reverification+at+summit+plan)

Output from cfg_interp_Run7.py, columns correspond to time in minutes, number of acquisitions, total image volume in TB

```
|B_protocol.cfg                     |    89.3 |   258 |  3.87 |
|B_protocol_excl_light.cfg          |    38.4 |    30 |  0.45 |
|C_protocol.cfg                     |    38.0 |   117 |  1.75 |
|D_protocol.cfg                     |    18.6 |    88 |  1.32 |
|sflat.cfg                          |    12.1 |    45 |  0.67 |
|test_flat.cfg                      |     0.9 |     3 |  0.04 |
````

### CODE REVIEW

**Comment by seanmacb** [comment]
Will need new path for `FILTERCONFIG`

**Comment by seanmacb** [comment]
Updated results from from `cfg_interp_Run7.py`

```
|B_protocol.cfg                     |    59.9 |   120 |  1.80 |
|B_protocol_excl_light.cfg          |    38.4 |    30 |  0.45 |
|C_protocol.cfg                     |    28.4 |    72 |  1.08 |
|D_protocol.cfg                     |     6.4 |    31 |  0.46 |
|sflat.cfg                          |    12.1 |    45 |  0.67 |
|test_flat.cfg                      |     0.9 |     3 |  0.04 |
```

**Review by jchiang87 — CHANGES_REQUESTED** [review]
As noted, please update `FILTERCONFIG` entries and remove `Run7/calib.cfg`, assuming it's redundant.

**Review by jchiang87 — CHANGES_REQUESTED** [review]
The `[FLAT]` acquisition sequences are all ordered by signal level, but their orders should be randomized.

**Comment by seanmacb** [comment]
From Aaron:

Before I forgot, following up our discussion of this for B sequences - one solution there is to make these monotonically increasing instead of randomized.  The randomization is to help separate out other effects (ie temp change) but we mostly understand that now

From me:

Ok, I can make that change with flat acquisitions, reordering the flat acquisitions in ascending flux levels
Should I preserve the older configurations with the flux levels randomized?

From Aaron:

Yes.  Suggest that we keep the same config for the inital B sequence run as Run 6, to be able to compare the results as similarly as possible. But then you could make this change for subsequence B protocols.
Although the change in placement of the projector may cause some differences anyway

**Review by jchiang87 — APPROVED** [review]
The discussion with Aaron makes sense, so lgtm.

**Pull request merged**
